#pragma once

#define EE_HANDS
#define SPLIT_WATCHDOG_ENABLE

#define MOUSEKEY_WHEEL_INTERVAL 16
#define MOUSEKEY_WHEEL_MAX_SPEED 60

#define AZOTEQ_IQS5XX_TPS65
#define AZOTEQ_IQS5XX_HOLD_TIME 220
#define AZOTEQ_IQS5XX_SCROLL_INITIAL_DISTANCE 5

#define WHEEL_EXTENDED_REPORT
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
#define POINTING_DEVICE_HIRES_SCROLL_MULTIPLIER 20
