LTO_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = azoteq_iqs5xx
AZOTEQ_IQS5XX_ZOOM_ENABLE = true
AZOTEQ_IQS5XX_SWIPE_INITIAL_DISTANCE = 100
